WIP: Trying something new

diff --git a/.github/workflows/pythonpackage.yml b/.github/workflows/pythonpackage.yml
--- a/.github/workflows/pythonpackage.yml
+++ b/.github/workflows/pythonpackage.yml
@@ -46,7 +46,24 @@ jobs:
       working-directory: ./docs
       run: |
         make html
-        git config --global user.name 'Github Action'
-        git config --global user.email 'action@github.com'
-        git commit -am "Documentation build Github Action"
-        git push origin HEAD:master
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/ARM-Development/RadTraQ.git --branch gh-pages --single-branch gh-pages
+        cd docs
+        make html
+        cp -r docs/build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # the return code.
+#    - name: Docs
+#      working-directory: ./docs
+#      run: |
+#        make html
+#        git config --global user.name 'Github Action'
+#        git config --global user.email 'action@github.com'
+#        git commit -am "Documentation build Github Action"
+#        git push origin HEAD:master
